/*
 * CreateVirtuvalMachineForm.java

 *
 * Created on __DATE__, __TIME__
 */

package com.nice.cloudservers;

import java.awt.Dimension;
import java.awt.Toolkit;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import org.springframework.beans.factory.BeanFactory;

import com.nice.bean.VirtuvalMachine;
import com.nice.dao.DataBaseDataSource;
import com.nice.dao.RegistrationDAO;

/**
 * 
 * @author __USER__
 */
public class CreateVirtuvalMachineForm extends javax.swing.JFrame {
	String balancerName;
	RegistrationDAO registrationDAO;

	/** Creates new form CreateNodeForm */
	public CreateVirtuvalMachineForm(String balancerName) {
		BeanFactory factory = new DataBaseDataSource().getDataFactory();
		registrationDAO = (RegistrationDAO) factory.getBean("registrationDAO");

		this.balancerName = balancerName;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

		// Determine the new location of the window
		int w = this.getSize().width;
		int h = this.getSize().height;
		int x = (dim.width - w) / 4;
		int y = (dim.height - h) / 4;

		// Move the window
		this.setLocation(x, y);
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jTextField5 = new javax.swing.JTextField();
		jTextField6 = new javax.swing.JTextField();
		jTextField7 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jTextField8 = new javax.swing.JTextField();
		jTextField9 = new javax.swing.JTextField();
		jLabel14 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("VirtuvalMachine");
		setBackground(new java.awt.Color(51, 51, 255));
		setForeground(new java.awt.Color(51, 51, 255));

		jLabel1.setFont(new java.awt.Font("Verdana", 1, 18));
		jLabel1.setForeground(new java.awt.Color(255, 0, 51));
		jLabel1.setText("Virtuval Machine");

		jLabel2.setFont(new java.awt.Font("Verdana", 1, 10));
		jLabel2.setText("Name :");

		jLabel3.setFont(new java.awt.Font("Verdana", 1, 10));
		jLabel3.setText("IPAddress :");

		jLabel4.setFont(new java.awt.Font("Verdana", 1, 10));
		jLabel4.setText("Region :");

		jLabel5.setFont(new java.awt.Font("Verdana", 1, 10));
		jLabel5.setText("CPU Capacity :");

		jLabel6.setFont(new java.awt.Font("Verdana", 1, 10));
		jLabel6.setText("Port :");

		jLabel7.setFont(new java.awt.Font("Verdana", 1, 10));
		jLabel7.setText("BandWidth :");

		jLabel8.setFont(new java.awt.Font("Verdana", 1, 10));
		jLabel8.setText("UsageCost :");

		jButton1.setFont(new java.awt.Font("Verdana", 1, 10));
		jButton1.setText("Create");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel9.setFont(new java.awt.Font("Verdana", 1, 10));
		jLabel9.setText("(Gflops)");

		jLabel10.setFont(new java.awt.Font("Verdana", 1, 10));
		jLabel10.setText("(Gbps)");

		jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11));
		jLabel11.setText("Frequency :");

		jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11));
		jLabel12.setText("Threshold :");

		jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11));
		jLabel13.setText("VM-Owner :");

		String cloudServerNames[] = registrationDAO.viewVMOnwers().split(",");
		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(
				cloudServerNames));

		jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11));
		jLabel14.setText("(hzs)");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				52,
																				52,
																				52)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel4)
																						.addComponent(
																								jLabel6)
																						.addComponent(
																								jLabel5)
																						.addComponent(
																								jLabel7)
																						.addComponent(
																								jLabel3)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jLabel8)
																						.addComponent(
																								jLabel11)
																						.addComponent(
																								jLabel12)
																						.addComponent(
																								jLabel13))
																		.addGap(
																				28,
																				28,
																				28)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel1)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																false)
																														.addComponent(
																																jTextField9,
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jTextField8,
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jComboBox1,
																																javax.swing.GroupLayout.Alignment.LEADING,
																																0,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																Short.MAX_VALUE)
																														.addComponent(
																																jTextField6,
																																javax.swing.GroupLayout.Alignment.LEADING,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																195,
																																Short.MAX_VALUE)
																														.addComponent(
																																jTextField5,
																																javax.swing.GroupLayout.Alignment.LEADING,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																94,
																																Short.MAX_VALUE)
																														.addComponent(
																																jTextField4,
																																javax.swing.GroupLayout.Alignment.LEADING,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																86,
																																Short.MAX_VALUE)
																														.addComponent(
																																jTextField3,
																																javax.swing.GroupLayout.Alignment.LEADING,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																118,
																																Short.MAX_VALUE)
																														.addComponent(
																																jTextField1,
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jTextField2,
																																javax.swing.GroupLayout.Alignment.LEADING,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																193,
																																Short.MAX_VALUE)
																														.addComponent(
																																jTextField7,
																																javax.swing.GroupLayout.Alignment.LEADING))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addGroup(
																												layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel14)
																														.addComponent(
																																jLabel9)
																														.addComponent(
																																jLabel10)))))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				176,
																				176,
																				176)
																		.addComponent(
																				jButton1)))
										.addContainerGap(91, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(25, 25, 25)
										.addComponent(jLabel1)
										.addGap(27, 27, 27)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(
																jTextField3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(
																jTextField4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(
																jTextField5,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel9))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel7)
														.addComponent(
																jTextField6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel10))
										.addGap(17, 17, 17)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField7,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel8))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel11)
														.addComponent(
																jTextField8,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel14))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel12)
														.addComponent(
																jTextField9,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel13)
														.addComponent(
																jComboBox1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												10, Short.MAX_VALUE)
										.addComponent(jButton1).addGap(20, 20,
												20)));

		pack();
	}// </editor-fold>

	// GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		JPanel jPanel = new JPanel();
		try {
			if (!jTextField1.getText().equals("")
					|| !jTextField3.getText().equals("")
					|| !jTextField3.getText().equals("")
					|| !jTextField4.getText().equals("")
					|| !jTextField5.getText().equals("")
					|| !jTextField6.getText().equals("")
					|| !jTextField7.getText().equals("")
					|| !jTextField8.getText().equals("")
					|| !jTextField9.getText().equals("")
					|| !jComboBox1.getSelectedItem().toString().equals("")) {

				VirtuvalMachine virtuvalMachine = new VirtuvalMachine();
				virtuvalMachine.setName(jTextField1.getText());
				virtuvalMachine.setVirtualip(jTextField2.getText());
				virtuvalMachine.setPort(jTextField3.getText());
				virtuvalMachine.setRegion(jTextField4.getText());
				virtuvalMachine.setBalancerName(balancerName);
				virtuvalMachine.setCpuCapacity(jTextField5.getText());
				virtuvalMachine.setBandWidth(jTextField6.getText());
				virtuvalMachine.setCost(jTextField7.getText());
				virtuvalMachine.setFrequency(jTextField8.getText());
				virtuvalMachine.setThreshold(jTextField9.getText());
				virtuvalMachine
						.setVmowner(jComboBox1.getSelectedItem().toString());

				boolean flag = registrationDAO.createVirtuvalMachines(
						virtuvalMachine).booleanValue();
				if (flag) {
					JOptionPane.showMessageDialog(jPanel,
							"Virtuval Machine Created SuccessFully");
				} else {
					JOptionPane.showMessageDialog(jPanel,
							"Virtuval Machine Created SuccessFully");
				}
			} else {
				JOptionPane
						.showMessageDialog(jPanel, "Please Enter All Fields");
			}

		} catch (Exception e) {
			System.out.println(e);
			JOptionPane.showMessageDialog(jPanel, "	Server Node Not Created");
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CreateVirtuvalMachineForm("").setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField8;
	private javax.swing.JTextField jTextField9;
	// End of variables declaration//GEN-END:variables

}