/*
 * PublicCloudOwnerForm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.nice.cloudservers;

import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.security.cert.X509Certificate;
import java.util.Iterator;
import java.util.TreeMap;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import org.springframework.beans.factory.BeanFactory;

import com.nice.bean.CloudServer;
import com.nice.bean.FileBean;
import com.nice.bean.Users;
import com.nice.dao.DataBaseDataSource;
import com.nice.dao.RegistrationDAO;
import com.nice.key.CryptMsgUtil;
import com.nice.key.X509V1Certificate;
import com.nice.user.DeleteFile;

/**
 * 
 * @author __USER__
 */
public class PublicCloudOwnerForm extends javax.swing.JFrame {

	Users users;
	TreeMap<Integer, Users> treeMap;
	RegistrationDAO registrationDAO;

	/** Creates new form PublicCloudOwnerForm */
	public PublicCloudOwnerForm(TreeMap<Integer, Users> treeMap, Users users) {
		BeanFactory factory = new DataBaseDataSource().getDataFactory();
		registrationDAO = (RegistrationDAO) factory.getBean("registrationDAO");
		this.treeMap = treeMap;
		this.users = users;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jFrame1 = new javax.swing.JFrame();
		jFrame2 = new javax.swing.JFrame();
		jFrame3 = new javax.swing.JFrame();
		jDialog1 = new javax.swing.JDialog();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jComboBox1 = new javax.swing.JComboBox();
		jButton2 = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable2 = new javax.swing.JTable();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jComboBox2 = new javax.swing.JComboBox();
		jButton8 = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jLabel18 = new javax.swing.JLabel();
		jLabel19 = new javax.swing.JLabel();
		jLabel20 = new javax.swing.JLabel();
		jPanel5 = new javax.swing.JPanel();
		jLabel21 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jScrollPane3 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList();
		jButton7 = new javax.swing.JButton();
		jLabel22 = new javax.swing.JLabel();
		jLabel23 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jComboBox3 = new javax.swing.JComboBox();

		javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(
				jFrame1.getContentPane());
		jFrame1.getContentPane().setLayout(jFrame1Layout);
		jFrame1Layout.setHorizontalGroup(jFrame1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
				Short.MAX_VALUE));
		jFrame1Layout.setVerticalGroup(jFrame1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300,
				Short.MAX_VALUE));

		javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(
				jFrame2.getContentPane());
		jFrame2.getContentPane().setLayout(jFrame2Layout);
		jFrame2Layout.setHorizontalGroup(jFrame2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
				Short.MAX_VALUE));
		jFrame2Layout.setVerticalGroup(jFrame2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300,
				Short.MAX_VALUE));

		javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(
				jFrame3.getContentPane());
		jFrame3.getContentPane().setLayout(jFrame3Layout);
		jFrame3Layout.setHorizontalGroup(jFrame3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
				Short.MAX_VALUE));
		jFrame3Layout.setVerticalGroup(jFrame3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300,
				Short.MAX_VALUE));

		javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(
				jDialog1.getContentPane());
		jDialog1.getContentPane().setLayout(jDialog1Layout);
		jDialog1Layout.setHorizontalGroup(jDialog1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400,
				Short.MAX_VALUE));
		jDialog1Layout.setVerticalGroup(jDialog1Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300,
				Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("PublicCloudOwner");

		jPanel1.setBackground(new java.awt.Color(204, 255, 204));
		jPanel1.setForeground(new java.awt.Color(153, 255, 255));

		jLabel1.setFont(new java.awt.Font("Verdana", 1, 18));
		jLabel1.setForeground(new java.awt.Color(255, 51, 51));
		jLabel1.setText("Cloud Servers");

		jButton1.setText("Create Cloud Server");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseExited(java.awt.event.MouseEvent evt) {
				jTable1MouseExited(evt);
			}
		});
		jTable1.addComponentListener(new java.awt.event.ComponentAdapter() {
			public void componentShown(java.awt.event.ComponentEvent evt) {
				// jTable1ComponentShown(evt);
			}
		});
		jTable1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
			public void mouseMoved(java.awt.event.MouseEvent evt) {
				jTable1MouseMoved(evt);
			}
		});
		jTable1.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				// jTable1FocusGained(evt);
			}
		});
		jScrollPane1.setViewportView(jTable1);

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));

		jButton2.setText("View Virtuval Machine");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton9.setText("changestatus");
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton9ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jComboBox1,
																								0,
																								167,
																								Short.MAX_VALUE)
																						.addComponent(
																								jButton9,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								167,
																								Short.MAX_VALUE))
																		.addGap(
																				36,
																				36,
																				36)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jButton1,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								257,
																								Short.MAX_VALUE)
																						.addComponent(
																								jButton2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								257,
																								Short.MAX_VALUE)))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				137,
																				137,
																				137)
																		.addComponent(
																				jLabel1))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel1Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				460,
																				Short.MAX_VALUE)))
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel1)
										.addGap(11, 11, 11)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												207, Short.MAX_VALUE)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jComboBox1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				jButton1)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jButton9)
														.addComponent(jButton2))
										.addGap(12, 12, 12)));

		jPanel2.setBackground(new java.awt.Color(204, 204, 255));

		jLabel2.setBackground(new java.awt.Color(0, 0, 0));
		jLabel2.setFont(new java.awt.Font("Verdana", 1, 14));
		jLabel2.setForeground(new java.awt.Color(255, 0, 51));
		jLabel2.setText("Virtuval Machine");

		jTable2.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseExited(java.awt.event.MouseEvent evt) {
				jTable2MouseExited(evt);
			}
		});
		jScrollPane2.setViewportView(jTable2);

		jButton3.setText("Create Virtuval Machine");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setText("Delete Virtuval Machine");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Item 1", "Item 2", "Item 3", "Item 4" }));

		jButton8.setText("ChangeStatus");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel2Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				jPanel2Layout
																						.createSequentialGroup()
																						.addContainerGap()
																						.addComponent(
																								jScrollPane2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.LEADING,
																				jPanel2Layout
																						.createSequentialGroup()
																						.addGap(
																								43,
																								43,
																								43)
																						.addGroup(
																								jPanel2Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING,
																												false)
																										.addComponent(
																												jButton8,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												Short.MAX_VALUE)
																										.addComponent(
																												jComboBox2,
																												0,
																												135,
																												Short.MAX_VALUE))
																						.addGap(
																								29,
																								29,
																								29)
																						.addGroup(
																								jPanel2Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(
																												jButton4,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												257,
																												Short.MAX_VALUE)
																										.addComponent(
																												jButton3,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												257,
																												Short.MAX_VALUE))))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jLabel2)))
										.addContainerGap()));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGap(7, 7, 7)
										.addComponent(jLabel2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jScrollPane2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												223,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(11, 11, 11)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton3)
														.addComponent(
																jComboBox2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton4)
														.addComponent(jButton8))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jPanel4.setBackground(new java.awt.Color(255, 204, 204));

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
		jLabel4.setText("VM-Owner Name :");

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
		jLabel5.setText("FileName :");

		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
		jLabel6.setText("VM-Name:");

		jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
		jLabel7.setText("Key :");

		jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
		jLabel8.setText("Signature :");

		jLabel20.setFont(new java.awt.Font("Verdana", 1, 14));
		jLabel20.setForeground(new java.awt.Color(255, 51, 51));
		jLabel20.setText("File Upload Details");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGap(
																				75,
																				75,
																				75)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel4)
																						.addComponent(
																								jLabel5)
																						.addComponent(
																								jLabel6)
																						.addComponent(
																								jLabel7)
																						.addComponent(
																								jLabel8))
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel4Layout
																										.createSequentialGroup()
																										.addGap(
																												15,
																												15,
																												15)
																										.addComponent(
																												jLabel12))
																						.addGroup(
																								jPanel4Layout
																										.createSequentialGroup()
																										.addGap(
																												18,
																												18,
																												18)
																										.addGroup(
																												jPanel4Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jLabel14)
																														.addComponent(
																																jLabel13)
																														.addComponent(
																																jLabel15)
																														.addComponent(
																																jLabel17)
																														.addComponent(
																																jLabel19)
																														.addComponent(
																																jLabel18)
																														.addComponent(
																																jLabel16)))))
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGap(
																				193,
																				193,
																				193)
																		.addComponent(
																				jLabel20)))
										.addContainerGap(140, Short.MAX_VALUE)));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGap(27, 27, 27)
										.addComponent(jLabel20)
										.addGap(36, 36, 36)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(jLabel12))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(jLabel13))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(jLabel14))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel7)
														.addComponent(jLabel15))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel8)
														.addComponent(jLabel16))
										.addGap(33, 33, 33)
										.addComponent(jLabel17)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jLabel18).addGap(20, 20,
												20).addComponent(jLabel19)
										.addContainerGap(110, Short.MAX_VALUE)));

		jPanel5.setBackground(new java.awt.Color(204, 204, 255));

		jLabel21.setFont(new java.awt.Font("Arial", 1, 12));
		jLabel21.setText("Upload FileHere :");

		jButton5.setText("Browse");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton6.setText("Upload");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		final String fileNames[] = registrationDAO.viewServerFiles().split(",");
		jList1.setModel(new javax.swing.AbstractListModel() {
			String[] strings = fileNames;

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane3.setViewportView(jList1);

		jButton7.setText("Download");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});

		jLabel22.setFont(new java.awt.Font("Verdana", 1, 14));
		jLabel22.setForeground(new java.awt.Color(255, 0, 0));
		jLabel22.setText("File Upload and Download :");

		jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/upload.jpg"))); // NOI18N

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
		jLabel3.setText("VM-Owners:");
		final String vmnames[] = registrationDAO.viewAllVMOnwers().split(",");
		jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(vmnames));

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout
				.setHorizontalGroup(jPanel5Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel5Layout.createSequentialGroup().addGap(
										30, 30, 30).addComponent(jLabel22)
										.addContainerGap(227, Short.MAX_VALUE))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel5Layout.createSequentialGroup().addGap(
										31, 31, 31).addComponent(jScrollPane3,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										130,
										javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(37, 37, 37).addComponent(
												jLabel23).addGap(112, 112, 112))
						.addGroup(
								jPanel5Layout.createSequentialGroup().addGap(
										81, 81, 81).addComponent(jButton7,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										263, Short.MAX_VALUE).addGap(126, 126,
										126))
						.addGroup(
								jPanel5Layout.createSequentialGroup().addGap(
										171, 171, 171).addComponent(jButton6)
										.addContainerGap(232, Short.MAX_VALUE))
						.addGroup(
								jPanel5Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel3)
														.addComponent(jLabel21))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jComboBox3,
																0,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																255,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jButton5)
										.addContainerGap(22, Short.MAX_VALUE)));
		jPanel5Layout
				.setVerticalGroup(jPanel5Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel5Layout
										.createSequentialGroup()
										.addGap(22, 22, 22)
										.addComponent(jLabel22)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												21, Short.MAX_VALUE)
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel21)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jButton5))
										.addGap(26, 26, 26)
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																jComboBox3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(20, 20, 20)
										.addComponent(jButton6)
										.addGap(18, 18, 18)
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jLabel23,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																124,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jScrollPane3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18).addComponent(
												jButton7).addGap(26, 26, 26)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jPanel5,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE))
														.addComponent(
																jPanel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jPanel4,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jPanel2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jPanel1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																jPanel2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jPanel4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jPanel5,
																0,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap()));

		pack();
	}// </editor-fold>

	// GEN-END:initComponents

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {

		try {
			String file = jList1.getSelectedValue().toString();
			if (!file.equals("")) {
				String downloadfile = registrationDAO.downloadFile(file);
				JFileChooser c = new JFileChooser();
				int x = c.showSaveDialog(null);
				if (x == JFileChooser.APPROVE_OPTION) {
					try {

						String saveFilename = null;
						String filename = new File(downloadfile).getName()
								.toString();
						System.out.println(filename);
						String[] token = filename.split("\\.");

						if (c.getSelectedFile() != null) {
							try {
								saveFilename = c.getSelectedFile() + "."
										+ token[1];
								FileInputStream fileInputStream = new FileInputStream(
										new File(downloadfile));
								FileOutputStream fileOutputStream = new FileOutputStream(
										saveFilename);
								int data;
								while ((data = fileInputStream.read()) != -1) {
									fileOutputStream.write(data);
								}
							} catch (Exception e) {
								// TODO: handle exception
							}
						} else {
							saveFilename = new File(downloadfile).getName()
									.toString();
						}
						System.out.println(saveFilename);
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
				String deletefile = new File("download").getAbsolutePath();
				new DeleteFile().deletemethod(deletefile);
				JOptionPane.showMessageDialog(null,
						"File Downloaded successfully", "Download File", 1);

			} else {
				JOptionPane.showMessageDialog(null, "Please Select One File",
						"Download File", 1);
			}

		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {

		FileBean fileBean = new FileBean();
		fileBean.setFilename(jTextField1.getText());
		fileBean.setVmowner(jComboBox3.getSelectedItem().toString());

		CryptMsgUtil decrypt = new CryptMsgUtil(new File(jTextField1.getText())
				.getName());
		String key = decrypt.encrypt(new File(jTextField1.getText()).getName());
		fileBean.setKey(key);

		X509V1Certificate certificate = certificate = new X509V1Certificate();
		X509Certificate cert = certificate.getCertificate();
		String[] s = String.valueOf(cert).split("Signature:");
		fileBean.setSignature(s[1].trim());
		String vmname = registrationDAO.uploadCloudFile(fileBean);

		jLabel12.setText(fileBean.getVmowner());
		jLabel13.setText(fileBean.getFilename());
		jLabel14.setText(vmname);
		jLabel15.setText(fileBean.getKey());
		jLabel16.setText(fileBean.getSignature());
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		browse();
	}

	private void browse() {
		// TODO Auto-generated method stub
		JFileChooser jfr = new JFileChooser();
		int check = jfr.showOpenDialog(this);
		try {
			if (check == JFileChooser.APPROVE_OPTION) {

				String path = jfr.getSelectedFile().getPath();

				jTextField1.setText(path);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void jTable2MouseExited(java.awt.event.MouseEvent evt) {
		String cloudServerName = jComboBox1.getSelectedItem().toString();
		Object obj[][] = registrationDAO.viewVirtuvalMachines(cloudServerName);
		Object string[] = registrationDAO.viewVirtuvalMachineMetaData();

		jTable2.setModel(new javax.swing.table.DefaultTableModel(obj, string));
		jScrollPane2.setViewportView(jTable2);

		jButton3.setText("Create Server Nodes");

		String serverNames = registrationDAO
				.viewVirtuvalMachineNames(cloudServerName);
		jButton4.setText("Delete Server Nodes");

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(serverNames
				.split(",")));
	}

	private void jTable1MouseExited(java.awt.event.MouseEvent evt) {
		Object obj[][] = registrationDAO.viewCloudServers();
		Object string[] = registrationDAO.viewCloudServerMetaData();

		jTable1.setModel(new javax.swing.table.DefaultTableModel(obj, string));
		jScrollPane1.setViewportView(jTable1);
		String cloudServerNames[] = registrationDAO.viewCloudServerNames()
				.split(",");
		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(
				cloudServerNames));
	}

	private void jTable1MouseMoved(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
		JPanel jPanel = new JPanel();
		String status = JOptionPane
				.showInputDialog("Please Enter Status Only Idle (or) Normal (or) Overload");

		if (status.toLowerCase().equals("idle")
				|| status.toLowerCase().equals("normal")
				|| status.toLowerCase().equals("overload")) {

			int flag = 0;
			try {
				flag = registrationDAO
						.changeServerNodeStatus(status.toLowerCase(),
								jComboBox2.getSelectedItem().toString());
			} catch (Exception e) {
				System.out.println(e);
			}
			if (flag > 0) {
				JOptionPane.showMessageDialog(jPanel,
						"Status Changed SuccessFully...");
			}
			repaint();
		} else {
			JOptionPane.showMessageDialog(jPanel, "Please Enter Proper String");
		}
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		JPanel jPanel = new JPanel();

		boolean flag = false;
		try {
			flag = registrationDAO.deleteServerNodes(jComboBox2
					.getSelectedItem().toString());
		} catch (Exception e) {
			System.out.println(e);
		}
		if (flag) {
			JOptionPane.showMessageDialog(jPanel,
					"Server Node Deleted SuccessFully...");
		} else {
			JOptionPane.showMessageDialog(jPanel,
					"Server Node Deleted SuccessFully...");
		}
	}

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
		JPanel jPanel = new JPanel();
		String status = JOptionPane
				.showInputDialog("Please Enter Statsu Only Idle (or) Normal (or) Overload");

		if (status.toLowerCase().equals("idle")
				|| status.toLowerCase().equals("normal")
				|| status.toLowerCase().equals("overload")) {

			int flag = 0;
			try {
				flag = registrationDAO.changeServerStatus(status.toLowerCase(),
						jComboBox1.getSelectedItem().toString());
			} catch (Exception e) {
				System.out.println(e);
			}
			if (flag > 0) {
				JOptionPane.showMessageDialog(jPanel,
						"Status Changed SuccessFully...");
			}
			repaint();
		} else {
			JOptionPane.showMessageDialog(jPanel, "Please Enter Proper String");
		}

	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		CreateVirtuvalMachineForm createNodeForm = new CreateVirtuvalMachineForm(
				jComboBox1.getSelectedItem().toString());
		createNodeForm.setVisible(true);

	}

	protected void jButton2ActionPerformed(ActionEvent evt) {
		String cloudServerName = jComboBox1.getSelectedItem().toString();
		Object obj[][] = registrationDAO.viewVirtuvalMachines(cloudServerName);
		Object string[] = registrationDAO.viewVirtuvalMachineMetaData();

		jTable2.setModel(new javax.swing.table.DefaultTableModel(obj, string));
		jScrollPane2.setViewportView(jTable2);

		jButton3.setText("Create Server Nodes");

		String serverNames = registrationDAO
				.viewVirtuvalMachineNames(cloudServerName);
		jButton4.setText("Delete Server Nodes");

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(serverNames
				.split(",")));

	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		CreateCloudServerForm createLoadBalancerForm = new CreateCloudServerForm(
				jComboBox1.getSelectedItem().toString());
		createLoadBalancerForm.setVisible(true);

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	/*
	 * public static void main(String args[]) {
	 * java.awt.EventQueue.invokeLater(new Runnable() { public void run() { new
	 * PublicCloudOwnerForm().setVisible(true); } }); }
	 */

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JComboBox jComboBox3;
	private javax.swing.JDialog jDialog1;
	private javax.swing.JFrame jFrame1;
	private javax.swing.JFrame jFrame2;
	private javax.swing.JFrame jFrame3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JList jList1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JTable jTable1;
	private javax.swing.JTable jTable2;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}