/*
 * AttackerForm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.nice.user;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.TreeMap;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import org.springframework.beans.factory.BeanFactory;

import com.nice.bean.FileBean;
import com.nice.bean.Users;
import com.nice.dao.DataBaseDataSource;
import com.nice.dao.RegistrationDAO;

/**
 * 
 * @author __USER__
 */
public class AttackerForm extends javax.swing.JFrame {
	Users users;
	RegistrationDAO registrationDAO;

	/** Creates new form AttackerForm */
	public AttackerForm(Users users) {
		BeanFactory factory = new DataBaseDataSource().getDataFactory();
		registrationDAO = (RegistrationDAO) factory.getBean("registrationDAO");
		this.users=users;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList();
		jButton1 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("AttackerWindow");

		final String fileNames[] = registrationDAO.viewServerFiles().split(",");
		jList1.setModel(new javax.swing.AbstractListModel() {
			String[] strings = fileNames;

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(jList1);

		jButton1.setFont(new java.awt.Font("Tahoma", 1, 11));
		jButton1.setForeground(new java.awt.Color(204, 0, 0));
		jButton1.setText("DOWNLOAD");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
		jLabel1.setForeground(new java.awt.Color(255, 0, 0));
		jLabel1.setText("FileName :");

		jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
		jLabel2.setForeground(new java.awt.Color(204, 0, 0));
		jLabel2.setText("File Actualsize :");

		jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
		jLabel3.setForeground(new java.awt.Color(204, 0, 0));
		jLabel3.setText("File Downloadsize :");

		jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
		jLabel4.setForeground(new java.awt.Color(204, 0, 0));
		jLabel4.setText("lossofPackets :");

		jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));

		jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));

		jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));

		jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));

		jMenu1.setText("File");

		jMenuItem1.setText("exit");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem1);

		jMenuBar1.add(jMenu1);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												180,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				70,
																				70,
																				70)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel1)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jLabel3)
																						.addComponent(
																								jLabel4))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel8)
																						.addComponent(
																								jLabel7)
																						.addComponent(
																								jLabel6)
																						.addComponent(
																								jLabel5)))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				58,
																				58,
																				58)
																		.addComponent(
																				jButton1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				190,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(91, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 444,
								Short.MAX_VALUE)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(68, 68, 68)
										.addComponent(jButton1)
										.addGap(59, 59, 59)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(jLabel5))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(jLabel6))
										.addGap(28, 28, 28)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(jLabel7))
										.addGap(27, 27, 27)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(jLabel8))
										.addContainerGap(165, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	// GEN-END:initComponents

	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			String file = jList1.getSelectedValue().toString();
			if (!file.equals("")) {
				FileBean fileBean = registrationDAO.attackerDownloadFile(file,users.getLoginid());
				String downloadfile = fileBean.getDecfilename();
				JFileChooser c = new JFileChooser();
				int x = c.showSaveDialog(null);
				if (x == JFileChooser.APPROVE_OPTION) {
					try {

						String saveFilename = null;
						String filename = new File(downloadfile).getName()
								.toString();
						System.out.println(filename);
						String[] token = filename.split("\\.");

						if (c.getSelectedFile() != null) {
							try {
								saveFilename = c.getSelectedFile() + "."
										+ token[1];
								FileInputStream fileInputStream = new FileInputStream(
										new File(downloadfile));
								FileOutputStream fileOutputStream = new FileOutputStream(
										saveFilename);
								int data;
								while ((data = fileInputStream.read()) != -1) {
									fileOutputStream.write(data);
								}
							} catch (Exception e) {
								// TODO: handle exception
							}
						} else {
							saveFilename = new File(downloadfile).getName()
									.toString();
						}
						System.out.println(saveFilename);
					}
					catch (Exception e) {
						e.printStackTrace();
					}
				}
				jLabel5.setText(fileBean.getFilename());
				jLabel7.setText(fileBean.getFiledownloadsize() + "");
				jLabel6.setText(fileBean.getFileactualsize() + "");
				jLabel8.setText(fileBean.getLossofpackets() + "");
				// String deletefile = new File("download").getAbsolutePath();
				// new DeleteFile().deletemethod(deletefile);
				JOptionPane
						.showMessageDialog(
								null,
								"File Downloaded successfully with some loss of packets",
								"Download File", 1);

			} else {
				JOptionPane.showMessageDialog(null, "Please Select One File",
						"Download File", 1);
			}

		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				//new AttackerForm().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JList jList1;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables

}