/*
 * MainForm.java
 *
 * Created on __DATE__, __TIME__
 */

package com.nice.user;

import java.util.TreeMap;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import org.springframework.beans.factory.BeanFactory;

import com.nice.bean.Users;
import com.nice.cloudservers.PublicCloudOwnerForm;
import com.nice.dao.DataBaseDataSource;
import com.nice.dao.RegistrationDAO;

/**
 * 
 * @author __USER__
 */
public class MainForm extends javax.swing.JFrame {
	RegistrationDAO registrationDAO;
	TreeMap<Integer, Users> treeMap = new TreeMap<Integer, Users>();

	/** Creates new form MainForm */
	public MainForm() {
		BeanFactory factory = new DataBaseDataSource().getDataFactory();
		registrationDAO = (RegistrationDAO) factory.getBean("registrationDAO");
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel2 = new javax.swing.JPanel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jLabel1 = new javax.swing.JLabel();
		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jPasswordField1 = new javax.swing.JPasswordField();
		jComboBox1 = new javax.swing.JComboBox();
		jLabel6 = new javax.swing.JLabel();
		jPanel3 = new javax.swing.JPanel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jPasswordField2 = new javax.swing.JPasswordField();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jComboBox2 = new javax.swing.JComboBox();
		jLabel11 = new javax.swing.JLabel();

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 100,
				Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 100,
				Short.MAX_VALUE));

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("MainForm");

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/head.png"))); // NOI18N
		jTabbedPane1.addTab("WELCOME", jLabel1);

		jLabel2.setFont(new java.awt.Font("Arial", 1, 12));
		jLabel2.setText("LoginID :");

		jLabel3.setFont(new java.awt.Font("Arial", 1, 12));
		jLabel3.setText("Password :");

		jLabel4.setFont(new java.awt.Font("Arial", 1, 12));
		jLabel4.setText("Login as :");

		jLabel5.setFont(new java.awt.Font("Arial", 1, 14));
		jLabel5.setForeground(new java.awt.Color(255, 0, 51));
		jLabel5.setText("LoginHere");

		jButton1.setFont(new java.awt.Font("Arial", 1, 12));
		jButton1.setText("Login");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Owner", "VmOwner", "User", "Attacker", "AttackerAnalyser" }));
		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});

		jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/login.jpg"))); // NOI18N

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(232, 232, 232)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel3)
														.addComponent(jLabel4)
														.addComponent(jLabel2))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jTextField1,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				161,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				58,
																				58,
																				58)
																		.addComponent(
																				jLabel5)
																		.addGap(
																				30,
																				30,
																				30))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jComboBox1,
																				0,
																				161,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jPasswordField1,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				161,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
										.addGap(8, 8, 8)
										.addComponent(
												jLabel6,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												147,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()).addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout.createSequentialGroup()
										.addContainerGap(396, Short.MAX_VALUE)
										.addComponent(jButton1).addGap(179,
												179, 179)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				33,
																				33,
																				33)
																		.addComponent(
																				jLabel5)
																		.addGap(
																				57,
																				57,
																				57)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel2)
																						.addComponent(
																								jTextField1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								17,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel3)
																						.addComponent(
																								jPasswordField1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				19,
																				19,
																				19)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel4)
																						.addComponent(
																								jComboBox1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				38,
																				38,
																				38)
																		.addComponent(
																				jButton1))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				79,
																				79,
																				79)
																		.addComponent(
																				jLabel6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				143,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(168, Short.MAX_VALUE)));

		jTabbedPane1.addTab("LOGIN", jPanel1);

		jLabel7.setFont(new java.awt.Font("Arial", 1, 12));
		jLabel7.setText("LoginID:");

		jLabel8.setFont(new java.awt.Font("Arial", 1, 12));
		jLabel8.setText("Password :");

		jLabel9.setFont(new java.awt.Font("Arial", 1, 12));
		jLabel9.setText("Location :");

		jLabel10.setFont(new java.awt.Font("Arial", 1, 12));
		jLabel10.setText("MailID :");

		jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource(
				"/images/register.jpg"))); // NOI18N

		jButton3.setFont(new java.awt.Font("Arial", 1, 12));
		jButton3.setText("Register");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"User", "Attacker", "VmOwner" }));
		jComboBox2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox2ActionPerformed(evt);
			}
		});

		jLabel11.setFont(new java.awt.Font("Arial", 1, 12));
		jLabel11.setText("Usertype :");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel3Layout
										.createSequentialGroup()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jButton3))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				21,
																				21,
																				21)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel3Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING)
																														.addComponent(
																																jLabel7)
																														.addComponent(
																																jLabel8)
																														.addComponent(
																																jLabel9)
																														.addComponent(
																																jLabel10))
																										.addGap(
																												3,
																												3,
																												3))
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel11)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jTextField4,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								350,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField3,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								350,
																								Short.MAX_VALUE)
																						.addComponent(
																								jPasswordField2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								350,
																								Short.MAX_VALUE)
																						.addComponent(
																								jTextField2,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								350,
																								Short.MAX_VALUE)
																						.addComponent(
																								jComboBox2,
																								javax.swing.GroupLayout.Alignment.LEADING,
																								0,
																								350,
																								Short.MAX_VALUE))))
										.addGap(29, 29, 29)
										.addComponent(
												jButton2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												163,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(59, 59, 59)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel7)
																						.addComponent(
																								jTextField2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				31,
																				31,
																				31)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel8)
																						.addComponent(
																								jPasswordField2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				32,
																				32,
																				32)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel9)
																						.addComponent(
																								jTextField3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(
																				21,
																				21,
																				21)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel10)
																						.addComponent(
																								jTextField4,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addComponent(jButton2))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jComboBox2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel11))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												72, Short.MAX_VALUE)
										.addComponent(jButton3).addGap(59, 59,
												59)));

		jTabbedPane1.addTab("REGISTER", jPanel3);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jTabbedPane1));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jTabbedPane1));

		pack();
	}// </editor-fold>

	// GEN-END:initComponents

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		String loginid = jTextField2.getText();
		String password = jPasswordField2.getText();
		String location = jTextField3.getText();
		String mailid = jTextField4.getText();

		Users users = new Users();
		users.setLoginid(loginid);
		users.setPassword(password);
		users.setLocation(location);
		users.setLogintype(jComboBox2.getActionCommand().toString());
		users.setMailid(mailid);

		JPanel jPanel = new JPanel();
		try {
			if (!loginid.equals("") && !password.equals("")) {

				boolean flag = registrationDAO.registerNewUser(users)
						.booleanValue();

				if (flag) {
					JOptionPane.showMessageDialog(jPanel,
							"Registration Success");
				} else {
					JOptionPane.showMessageDialog(jPanel,
							"Registration Success");
				}
			} else {
				JOptionPane.showMessageDialog(jPanel,
						"Please Enter Loginname & password");
			}
		} catch (Exception e) {
			e.printStackTrace();
			System.out.println(e);
			JOptionPane.showMessageDialog(jPanel, "Registration Fail");
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String loginname = jTextField1.getText();
		String password = jPasswordField1.getText();
		String usertype = jComboBox1.getSelectedItem().toString();

		JPanel jpanel = new JPanel();
		if (loginname.equals("")) {
			JOptionPane.showMessageDialog(jpanel, "Please Enter LoginName");
		}
		if (password.equals("")) {
			JOptionPane.showMessageDialog(jpanel, "Please Enter Password");
		}
		try {
			if (!loginname.equals("") && !password.equals("")
					&& !usertype.equals("")) {

				Users users = registrationDAO.loginCheck(new Users(loginname,
						password, usertype));
				if (users != null) {
					if (users.getLogintype().equalsIgnoreCase("owner")) {
						PublicCloudOwnerForm publicCloudOwnerForm = new PublicCloudOwnerForm(
								treeMap, users);
						publicCloudOwnerForm.setVisible(true);
					} else if (users.getLogintype().equalsIgnoreCase("vmowner")) {
						OwnerForm ownerForm = new OwnerForm(users);
						ownerForm.setVisible(true);
					} else if (users.getLogintype()
							.equalsIgnoreCase("attacker")) {
						AttackerForm attackerForm = new AttackerForm(users);
						attackerForm.setVisible(true);
					} else if (users.getLogintype().equalsIgnoreCase(
							"attackeranalyser")) {
						AttackAnalyserForm attackAnalyserForm = new AttackAnalyserForm(
								users,treeMap);
						attackAnalyserForm.setVisible(true);
					} else if (users.getLogintype().equalsIgnoreCase("user")) {
						Users taskrequest = new Users();

						taskrequest.setUserid(users.getUserid());
						taskrequest.setLoginid(users.getLoginid());
						taskrequest
								.setRegistereddate(users.getRegistereddate());
						taskrequest.setLogintype(users.getLogintype());
						taskrequest.setLocation(users.getLocation());
						taskrequest.setMailid(users.getMailid());
						UsersForm usersForm = new UsersForm(treeMap,
								taskrequest);
						usersForm.setVisible(true);
					} else {
						OwnerForm ownerForm = new OwnerForm(users);
						ownerForm.setVisible(true);
					}
				} else {
					JOptionPane.showMessageDialog(jpanel,
							"Wrong loginid and password");
				}
			}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(jpanel,
					"INVALID USER PLEASE TRY AGAIN");

		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		JFrame.setDefaultLookAndFeelDecorated(true);
		/*
		 * SubstanceLookAndFeel
		 * .setCurrentTheme("org.jvnet.substance.theme.SubstanceAquaTheme");
		 * SubstanceLookAndFeel
		 * .setCurrentButtonShaper("org.jvnet.substance.button.StandardButtonShaper"
		 * ); SubstanceLookAndFeel
		 * .setCurrentGradientPainter("SpecularGradientPainter");
		 */java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainForm().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JPasswordField jPasswordField2;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	// End of variables declaration//GEN-END:variables

}